 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: deploy
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: web
     spec:
       containers:
         - name: micro-servizio-one
           image: micro1:c1
           ports:
             - containerPort: 8080
         - name: micro-servizio-two
           image: micro2:c2
           #ports:
            # - containerPort: 8090